import { MaterialType } from '../materials';
import { CraftingRecipe } from './models';

export const craftingRecipes: CraftingRecipe[] = [
  {
    outputMaterial: MaterialType.HPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 10 },
      { type: MaterialType.ShyWildFlower, amount: 5 },
    ],
    requiredGold: 0,
    requiredActionEnergy: 1,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.MajorHPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 18 },
      { type: MaterialType.ShyWildFlower, amount: 9 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ElementalHPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 48 },
      { type: MaterialType.ShyWildFlower, amount: 24 },
      { type: MaterialType.BrightWildFlower, amount: 6 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidElementalHPPotion,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.ElementalHPPotion, amount: 3 },
      { type: MaterialType.BrightWildFlower, amount: 8 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 360,
    seconds: 75 * 60,
  },
  {
    outputMaterial: MaterialType.SacredBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.IronOre, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ElectricGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.IronOre, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.FlameGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.TenderTimber, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ClayGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.IronOre, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.FrostGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.IronOre, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.DarkGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.TenderTimber, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.CorrosiveBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.HeavyIronOre, amount: 6 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.FlashGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.IronOre, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SleepBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
      { type: MaterialType.IronOre, amount: 10 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.DestructionBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.HeavyIronOre, amount: 6 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.WhirlwindGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.TenderTimber, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ThunderPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 32 },
      { type: MaterialType.ShyWildFlower, amount: 16 },
      { type: MaterialType.BrightWildFlower, amount: 4 },
      { type: MaterialType.RareRelic, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidCorrosionBomb,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.CorrosiveBomb, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 2 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidSacredBomb,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.SacredBomb, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidDestructionBomb,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.DestructionBomb, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 2 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidFrostGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.FrostGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidFlameGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.FlameGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidWhirlwindGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.WhirlwindGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidSleepBomb,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.SleepBomb, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 2 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidDarkGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.DarkGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidClayGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.ClayGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidThunderPotion,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.ThunderPotion, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 10 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidFlashGrenade,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.FlashGrenade, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.Flare,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 35 },
      { type: MaterialType.NaturalPearl, amount: 20 },
    ],
    requiredGold: 0,
    requiredActionEnergy: 1,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.SplendidFlare,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.Flare, amount: 3 },
      { type: MaterialType.ShyWildFlower, amount: 20 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 45 * 60,
  },
  {
    outputMaterial: MaterialType.TauntingScarecrow,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.Timber, amount: 13 },
      { type: MaterialType.FreshMushroom, amount: 15 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.CamouflageRobe,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ToughLeather, amount: 22 },
      { type: MaterialType.CrudeMushroom, amount: 35 },
      { type: MaterialType.FreshMushroom, amount: 22 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.RepairShopPortalScroll,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.BrightWildFlower, amount: 18 },
      { type: MaterialType.NaturalPearl, amount: 16 },
      { type: MaterialType.WildFlower, amount: 144 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.Panacea,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 16 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
      { type: MaterialType.RareRelic, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.PheromoneBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.HeavyIronOre, amount: 6 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.Campfire,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
      { type: MaterialType.FreshMushroom, amount: 15 },
      { type: MaterialType.Timber, amount: 12 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SacredCharm,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 30 },
      { type: MaterialType.FreshMushroom, amount: 18 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidSacredCharm,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.SacredCharm, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidDisguiseRobe,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.CamouflageRobe, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 9 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidTauntingScarecrow,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.TauntingScarecrow, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 7 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidCampfire,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.Campfire, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 6 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidPanacea,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.Panacea, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 10 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.StealthRobe,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ExquisiteMushroom, amount: 5 },
      { type: MaterialType.FreshMushroom, amount: 15 },
      { type: MaterialType.StrongIronOre, amount: 2 },
      { type: MaterialType.ToughLeather, amount: 2 },
      { type: MaterialType.CrudeMushroom, amount: 35 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.LuterrasHorn,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.BrightWildFlower, amount: 4 },
      { type: MaterialType.StrongIronOre, amount: 2 },
      { type: MaterialType.ShyWildFlower, amount: 20 },
      { type: MaterialType.WildFlower, amount: 40 },
      { type: MaterialType.IronOre, amount: 2 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.TimeStopPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.BrightWildFlower, amount: 5 },
      { type: MaterialType.SturdyTimber, amount: 2 },
      { type: MaterialType.ShyWildFlower, amount: 20 },
      { type: MaterialType.RareRelic, amount: 2 },
      { type: MaterialType.WildFlower, amount: 40 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidStealthRobe,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.StealthRobe, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 10 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ProtectivePotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
      { type: MaterialType.FreshMushroom, amount: 16 },
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.RareRelic, amount: 5 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.MarchingFlag,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
      { type: MaterialType.NaturalPearl, amount: 8 },
      { type: MaterialType.CrudeMushroom, amount: 38 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SwiftnessRobe,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ToughLeather, amount: 17 },
      { type: MaterialType.BrightWildFlower, amount: 17 },
      { type: MaterialType.WildFlower, amount: 17 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidMarchingFlag,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.MarchingFlag, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidProtectivePotion,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.ProtectivePotion, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 10 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.SplendidSprintersRobe,
    amount: 2,
    requiredMaterials: [
      { type: MaterialType.MarchingFlag, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.Stimulant,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.ExquisiteMushroom, amount: 5 },
      { type: MaterialType.FreshMushroom, amount: 20 },
      { type: MaterialType.SturdyTimber, amount: 4 },
      { type: MaterialType.RareRelic, amount: 4 },
      { type: MaterialType.CrudeMushroom, amount: 40 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.AdrophinePotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.BrightWildFlower, amount: 6 },
      { type: MaterialType.StrongIronOre, amount: 2 },
      { type: MaterialType.ShyWildFlower, amount: 24 },
      { type: MaterialType.RareRelic, amount: 2 },
      { type: MaterialType.WildFlower, amount: 48 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.MastersChewyGrilledSkewers,
    amount: 10,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 6 },
      { type: MaterialType.OrehaSolarCarp, amount: 5 },
      { type: MaterialType.TreatedMeat, amount: 24 },
      { type: MaterialType.RedfleshFish, amount: 20 },
      { type: MaterialType.ThickRawMeat, amount: 48 },
      { type: MaterialType.Fish, amount: 40 },
    ],
    requiredGold: 35,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.MastersMoistOmelet,
    amount: 10,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 6 },
      { type: MaterialType.OrehaSolarCarp, amount: 5 },
      { type: MaterialType.TreatedMeat, amount: 24 },
      { type: MaterialType.RedfleshFish, amount: 20 },
      { type: MaterialType.ThickRawMeat, amount: 48 },
      { type: MaterialType.Fish, amount: 40 },
    ],
    requiredGold: 35,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.MastersSaltyStew,
    amount: 10,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 6 },
      { type: MaterialType.OrehaSolarCarp, amount: 5 },
      { type: MaterialType.TreatedMeat, amount: 24 },
      { type: MaterialType.RedfleshFish, amount: 20 },
      { type: MaterialType.ThickRawMeat, amount: 48 },
      { type: MaterialType.Fish, amount: 40 },
    ],
    requiredGold: 35,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.MastersHerbSteakMeal,
    amount: 10,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 12 },
      { type: MaterialType.OrehaSolarCarp, amount: 10 },
      { type: MaterialType.TreatedMeat, amount: 48 },
      { type: MaterialType.RedfleshFish, amount: 40 },
      { type: MaterialType.ThickRawMeat, amount: 96 },
      { type: MaterialType.Fish, amount: 80 },
    ],
    requiredGold: 50,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrThickRawMeat, amount: 9 },
      { type: MaterialType.ToughLeather, amount: 36 },
      { type: MaterialType.ThickRawMeat, amount: 72 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 9 },
      { type: MaterialType.ToughLeather, amount: 36 },
      { type: MaterialType.ThickRawMeat, amount: 72 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 10 },
      { type: MaterialType.ToughLeather, amount: 40 },
      { type: MaterialType.ThickRawMeat, amount: 80 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrSolarCarp, amount: 9 },
      { type: MaterialType.NaturalPearl, amount: 36 },
      { type: MaterialType.Fish, amount: 72 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaSolarCarp, amount: 9 },
      { type: MaterialType.NaturalPearl, amount: 36 },
      { type: MaterialType.Fish, amount: 72 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaSolarCarp, amount: 10 },
      { type: MaterialType.NaturalPearl, amount: 40 },
      { type: MaterialType.Fish, amount: 80 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrRelic, amount: 7 },
      { type: MaterialType.RareRelic, amount: 28 },
      { type: MaterialType.AncientRelic, amount: 56 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaRelic, amount: 7 },
      { type: MaterialType.RareRelic, amount: 28 },
      { type: MaterialType.AncientRelic, amount: 56 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaRelic, amount: 8 },
      { type: MaterialType.RareRelic, amount: 26 },
      { type: MaterialType.AncientRelic, amount: 64 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
];
