import { MaterialType } from '../materials';
import { CraftingRecipe } from './models';

export const craftingRecipes: CraftingRecipe[] = [
  {
    outputMaterial: MaterialType.HPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 10 },
      { type: MaterialType.ShyWildFlower, amount: 5 },
    ],
    requiredGold: 0,
    requiredActionEnergy: 1,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.MajorHPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 18 },
      { type: MaterialType.ShyWildFlower, amount: 9 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.ElementalHPPotion,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 48 },
      { type: MaterialType.ShyWildFlower, amount: 24 },
      { type: MaterialType.BrightWildFlower, amount: 6 },
    ],
    requiredGold: 30,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.DestructionBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.HeavyIronOre, amount: 6 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.PheromoneBomb,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 32 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.HeavyIronOre, amount: 6 },
      { type: MaterialType.ExquisiteMushroom, amount: 4 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.WhirlwindGrenade,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 24 },
      { type: MaterialType.FreshMushroom, amount: 12 },
      { type: MaterialType.TenderTimber, amount: 3 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.Flare,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.WildFlower, amount: 35 },
      { type: MaterialType.NaturalPearl, amount: 20 },
    ],
    requiredGold: 0,
    requiredActionEnergy: 1,
    seconds: 10,
  },
  {
    outputMaterial: MaterialType.SacredCharm,
    amount: 3,
    requiredMaterials: [
      { type: MaterialType.CrudeMushroom, amount: 30 },
      { type: MaterialType.FreshMushroom, amount: 18 },
      { type: MaterialType.ExquisiteMushroom, amount: 3 },
    ],
    requiredGold: 15,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrThickRawMeat, amount: 9 },
      { type: MaterialType.ToughLeather, amount: 36 },
      { type: MaterialType.ThickRawMeat, amount: 72 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 9 },
      { type: MaterialType.ToughLeather, amount: 36 },
      { type: MaterialType.ThickRawMeat, amount: 72 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaThickMeat, amount: 10 },
      { type: MaterialType.ToughLeather, amount: 40 },
      { type: MaterialType.ThickRawMeat, amount: 80 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrSolarCarp, amount: 9 },
      { type: MaterialType.NaturalPearl, amount: 36 },
      { type: MaterialType.Fish, amount: 72 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaSolarCarp, amount: 9 },
      { type: MaterialType.NaturalPearl, amount: 36 },
      { type: MaterialType.Fish, amount: 72 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaSolarCarp, amount: 10 },
      { type: MaterialType.NaturalPearl, amount: 40 },
      { type: MaterialType.Fish, amount: 80 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
  {
    outputMaterial: MaterialType.CaldarrFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.CaldarrRelic, amount: 7 },
      { type: MaterialType.RareRelic, amount: 28 },
      { type: MaterialType.AncientRelic, amount: 56 },
    ],
    requiredGold: 80,
    requiredActionEnergy: 300,
    seconds: 60 * 60,
  },
  {
    outputMaterial: MaterialType.SimpleOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaRelic, amount: 7 },
      { type: MaterialType.RareRelic, amount: 28 },
      { type: MaterialType.AncientRelic, amount: 56 },
    ],
    requiredGold: 200,
    requiredActionEnergy: 150,
    seconds: 30 * 60,
  },
  {
    outputMaterial: MaterialType.BasicOrehaFusionMaterial,
    amount: 30,
    requiredMaterials: [
      { type: MaterialType.OrehaRelic, amount: 8 },
      { type: MaterialType.RareRelic, amount: 26 },
      { type: MaterialType.AncientRelic, amount: 64 },
    ],
    requiredGold: 204,
    requiredActionEnergy: 215,
    seconds: 43 * 60,
  },
];
