import { Rarity } from '../models/index';
import { SingleLevelHoning } from './models';
import { feed, upgradeLegendary, upgradeRelic } from './utils';

export const legendaryArmorHoningCosts: SingleLevelHoning[] = [
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 39424, shards: 2464 }),
    upgrade: upgradeLegendary('armor', {
      silver: 20000,
      gold: 160,
      shards: 58,
      basicOreha: 4,
      crystals: 216,
      greatLeapStone: 4,
    }),
    fromLevel: 0,
    toLevel: 1,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 39424, shards: 2464 }),
    upgrade: upgradeLegendary('armor', {
      silver: 19800,
      gold: 160,
      shards: 58,
      basicOreha: 4,
      crystals: 216,
      greatLeapStone: 6,
    }),
    fromLevel: 1,
    toLevel: 2,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 39424, shards: 2464 }),
    upgrade: upgradeLegendary('armor', {
      silver: 20300,
      gold: 170,
      shards: 58,
      basicOreha: 4,
      crystals: 216,
      greatLeapStone: 6,
    }),
    fromLevel: 2,
    toLevel: 3,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 56704, shards: 3544 }),
    upgrade: upgradeLegendary('armor', {
      silver: 20800,
      gold: 170,
      shards: 82,
      basicOreha: 4,
      crystals: 310,
      greatLeapStone: 6,
    }),
    fromLevel: 3,
    toLevel: 4,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 56704, shards: 3544 }),
    upgrade: upgradeLegendary('armor', {
      silver: 21300,
      gold: 170,
      shards: 82,
      basicOreha: 4,
      crystals: 310,
      greatLeapStone: 6,
    }),
    fromLevel: 4,
    toLevel: 5,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 56704, shards: 3544 }),
    upgrade: upgradeLegendary('armor', {
      silver: 21820,
      gold: 170,
      shards: 82,
      basicOreha: 4,
      crystals: 310,
      greatLeapStone: 8,
    }),
    fromLevel: 5,
    toLevel: 6,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 73952, shards: 4622 }),
    upgrade: upgradeLegendary('armor', {
      silver: 22380,
      gold: 170,
      shards: 108,
      basicOreha: 6,
      crystals: 404,
      greatLeapStone: 8,
    }),
    fromLevel: 6,
    toLevel: 7,
    chance: {
      maxAttempts: 5,
      reducedAttempts: 4,
      start: 60,
      increase: 6,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 73952, shards: 4622 }),
    upgrade: upgradeLegendary('armor', {
      silver: 22920,
      gold: 170,
      shards: 108,
      basicOreha: 6,
      crystals: 404,
      greatLeapStone: 10,
    }),
    fromLevel: 7,
    toLevel: 8,
    chance: {
      maxAttempts: 6,
      reducedAttempts: 5,
      start: 45,
      increase: 4.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 73952, shards: 4622 }),
    upgrade: upgradeLegendary('armor', {
      silver: 23480,
      gold: 170,
      shards: 108,
      basicOreha: 6,
      crystals: 404,
      greatLeapStone: 10,
    }),
    fromLevel: 8,
    toLevel: 9,
    chance: {
      maxAttempts: 7,
      reducedAttempts: 6,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 45600, shards: 5700 }),
    upgrade: upgradeLegendary('armor', {
      silver: 24040,
      gold: 170,
      shards: 132,
      basicOreha: 8,
      crystals: 498,
      greatLeapStone: 10,
    }),
    fromLevel: 9,
    toLevel: 10,
    chance: {
      maxAttempts: 7,
      reducedAttempts: 6,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 45600, shards: 5700 }),
    upgrade: upgradeLegendary('armor', {
      silver: 24640,
      gold: 170,
      shards: 132,
      basicOreha: 8,
      crystals: 498,
      greatLeapStone: 10,
    }),
    fromLevel: 10,
    toLevel: 11,
    chance: {
      maxAttempts: 7,
      reducedAttempts: 6,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 45600, shards: 5700 }),
    upgrade: upgradeLegendary('armor', {
      silver: 25240,
      gold: 170,
      shards: 132,
      basicOreha: 8,
      crystals: 498,
      greatLeapStone: 12,
    }),
    fromLevel: 11,
    toLevel: 12,
    chance: {
      maxAttempts: 11,
      reducedAttempts: 9,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 54224, shards: 6778 }),
    upgrade: upgradeLegendary('armor', {
      silver: 25860,
      gold: 170,
      shards: 158,
      basicOreha: 8,
      crystals: 592,
      greatLeapStone: 12,
    }),
    fromLevel: 12,
    toLevel: 13,
    chance: {
      maxAttempts: 11,
      reducedAttempts: 9,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 54224, shards: 6778 }),
    upgrade: upgradeLegendary('armor', {
      silver: 26500,
      gold: 170,
      shards: 158,
      basicOreha: 8,
      crystals: 592,
      greatLeapStone: 12,
    }),
    fromLevel: 13,
    toLevel: 14,
    chance: {
      maxAttempts: 11,
      reducedAttempts: 9,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 54224, shards: 6778 }),
    upgrade: upgradeLegendary('armor', {
      silver: 27160,
      gold: 180,
      shards: 158,
      basicOreha: 8,
      crystals: 592,
      greatLeapStone: 12,
    }),
    fromLevel: 14,
    toLevel: 15,
    chance: {
      maxAttempts: 15,
      reducedAttempts: 10,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 146848, shards: 9178 }),
    upgrade: upgradeLegendary('armor', {
      silver: 27820,
      gold: 210,
      shards: 216,
      basicOreha: 9,
      crystals: 686,
      greatLeapStone: 14,
    }),
    fromLevel: 15,
    toLevel: 16,
    chance: {
      maxAttempts: 15,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 198496, shards: 12406 }),
    upgrade: upgradeLegendary('armor', {
      silver: 28420,
      gold: 250,
      shards: 292,
      basicOreha: 10,
      crystals: 686,
      greatLeapStone: 16,
    }),
    fromLevel: 16,
    toLevel: 17,
    chance: {
      maxAttempts: 15,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 269184, shards: 16824 }),
    upgrade: upgradeLegendary('armor', {
      silver: 29040,
      gold: 280,
      shards: 396,
      basicOreha: 12,
      crystals: 686,
      greatLeapStone: 16,
    }),
    fromLevel: 17,
    toLevel: 18,
    chance: {
      maxAttempts: 26,
      start: 5,
      increase: 0.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 370656, shards: 23166 }),
    upgrade: upgradeLegendary('armor', {
      silver: 29660,
      gold: 320,
      shards: 536,
      basicOreha: 14,
      crystals: 780,
      greatLeapStone: 18,
    }),
    fromLevel: 18,
    toLevel: 19,
    chance: {
      maxAttempts: 26,
      start: 5,
      increase: 0.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'armor',
    feed: feed({ silver: 503424, shards: 31464 }),
    upgrade: upgradeLegendary('armor', {
      silver: 30320,
      gold: 350,
      shards: 728,
      basicOreha: 14,
      crystals: 780,
      greatLeapStone: 20,
    }),
    fromLevel: 19,
    toLevel: 20,
    chance: {
      maxAttempts: 40,
      start: 3,
      increase: 0.3,
    },
  },
];

export const relicArmorHoningCosts: SingleLevelHoning[] = [
  {
    rarirty: Rarity.Relic,
    itemType: 'armor',
    feed: feed({ silver: 683232, shards: 42702 }),
    upgrade: upgradeRelic('armor', {
      silver: 30980,
      gold: 360,
      shards: 988,
      basicOreha: 16,
      crystals: 780,
      greatLeapStone: 22,
    }),
    fromLevel: 20,
    toLevel: 21,
    chance: {
      maxAttempts: 40,
      start: 3,
      increase: 0.3,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'armor',
    feed: feed({ silver: 917568, shards: 57348 }),
    upgrade: upgradeRelic('armor', {
      silver: 31640,
      gold: 360,
      shards: 1340,
      basicOreha: 18,
      crystals: 874,
      greatLeapStone: 24,
    }),
    fromLevel: 21,
    toLevel: 22,
    chance: {
      maxAttempts: 111,
      start: 1,
      increase: 0.1,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'armor',
    feed: feed({ silver: 1244864, shards: 77804 }),
    upgrade: upgradeRelic('armor', {
      silver: 32320,
      gold: 390,
      shards: 1818,
      basicOreha: 20,
      crystals: 874,
      greatLeapStone: 26,
    }),
    fromLevel: 22,
    toLevel: 23,
    chance: {
      maxAttempts: 111,
      start: 1,
      increase: 0.1,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'armor',
    feed: feed({ silver: 1688576, shards: 105536 }),
    upgrade: upgradeRelic('armor', {
      silver: 33040,
      gold: 400,
      shards: 2466,
      basicOreha: 22,
      crystals: 874,
      greatLeapStone: 28,
    }),
    fromLevel: 23,
    toLevel: 24,
    chance: {
      maxAttempts: 219,
      start: 0.5,
      increase: 0.05,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'armor',
    feed: feed({ silver: 2311808, shards: 144488 }),
    upgrade: upgradeRelic('armor', {
      silver: 33740,
      gold: 420,
      shards: 3346,
      basicOreha: 24,
      crystals: 968,
      greatLeapStone: 30,
    }),
    fromLevel: 24,
    toLevel: 25,
    chance: {
      maxAttempts: 219,
      start: 0.5,
      increase: 0.05,
    },
  },
];

export const armorHoningCosts = [
  ...legendaryArmorHoningCosts,
  ...relicArmorHoningCosts,
];
