import { Rarity } from '../models/index';
import { SingleLevelHoning } from './models';
import { feed, upgradeLegendary, upgradeRelic } from './utils';

export const legendaryWeaponHoningCosts: SingleLevelHoning[] = [
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 56416, shards: 3610 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 56416,
      gold: 300,
      shards: 84,
      basicOreha: 4,
      crystals: 358,
      greatLeapStone: 6,
    }),
    fromLevel: 0,
    toLevel: 1,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 56416, shards: 3526 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 28280,
      gold: 300,
      shards: 84,
      basicOreha: 4,
      crystals: 358,
      greatLeapStone: 8,
    }),
    fromLevel: 1,
    toLevel: 2,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 56416, shards: 3526 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 20300,
      gold: 300,
      shards: 84,
      basicOreha: 4,
      crystals: 358,
      greatLeapStone: 8,
    }),
    fromLevel: 2,
    toLevel: 3,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 81088, shards: 5068 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 29680,
      gold: 300,
      shards: 120,
      basicOreha: 6,
      crystals: 516,
      greatLeapStone: 10,
    }),
    fromLevel: 3,
    toLevel: 4,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 81088, shards: 5068 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 30420,
      gold: 300,
      shards: 120,
      basicOreha: 6,
      crystals: 516,
      greatLeapStone: 10,
    }),
    fromLevel: 4,
    toLevel: 5,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 81088, shards: 5068 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 31160,
      gold: 320,
      shards: 120,
      basicOreha: 6,
      crystals: 516,
      greatLeapStone: 12,
    }),
    fromLevel: 5,
    toLevel: 6,
    chance: {
      maxAttempts: 1,
      start: 100,
      increase: 0,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 105760, shards: 6610 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 31920,
      gold: 320,
      shards: 156,
      basicOreha: 6,
      crystals: 672,
      greatLeapStone: 12,
    }),
    fromLevel: 6,
    toLevel: 7,
    chance: {
      maxAttempts: 5,
      start: 60,
      increase: 6,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 105760, shards: 6610 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 32700,
      gold: 320,
      shards: 156,
      basicOreha: 6,
      crystals: 672,
      greatLeapStone: 14,
    }),
    fromLevel: 7,
    toLevel: 8,
    chance: {
      maxAttempts: 6,
      start: 45,
      increase: 4,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 105760, shards: 6610 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 33520,
      gold: 320,
      shards: 192,
      basicOreha: 8,
      crystals: 672,
      greatLeapStone: 14,
    }),
    fromLevel: 8,
    toLevel: 9,
    chance: {
      maxAttempts: 7,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 65216, shards: 8152 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 34340,
      gold: 320,
      shards: 192,
      basicOreha: 8,
      crystals: 830,
      greatLeapStone: 16,
    }),
    fromLevel: 9,
    toLevel: 10,
    chance: {
      maxAttempts: 7,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 65216, shards: 8152 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 35180,
      gold: 330,
      shards: 192,
      basicOreha: 8,
      crystals: 830,
      greatLeapStone: 16,
    }),
    fromLevel: 10,
    toLevel: 11,
    chance: {
      maxAttempts: 7,
      start: 30,
      increase: 3,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 65216, shards: 8152 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 36040,
      gold: 330,
      shards: 192,
      basicOreha: 8,
      crystals: 830,
      greatLeapStone: 18,
    }),
    fromLevel: 11,
    toLevel: 12,
    chance: {
      maxAttempts: 11,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 77568, shards: 9696 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 36940,
      gold: 330,
      shards: 228,
      basicOreha: 10,
      crystals: 986,
      greatLeapStone: 18,
    }),
    fromLevel: 12,
    toLevel: 13,
    chance: {
      maxAttempts: 11,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 77568, shards: 9696 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 37840,
      gold: 330,
      shards: 228,
      basicOreha: 10,
      crystals: 986,
      greatLeapStone: 20,
    }),
    fromLevel: 13,
    toLevel: 14,
    chance: {
      maxAttempts: 11,
      start: 15,
      increase: 1.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 77568, shards: 9696 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 38760,
      gold: 330,
      shards: 228,
      basicOreha: 10,
      crystals: 986,
      greatLeapStone: 20,
    }),
    fromLevel: 14,
    toLevel: 15,
    chance: {
      maxAttempts: 15,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 208224, shards: 13014 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 39720,
      gold: 410,
      shards: 310,
      basicOreha: 12,
      crystals: 1144,
      greatLeapStone: 22,
    }),
    fromLevel: 15,
    toLevel: 16,
    chance: {
      maxAttempts: 15,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 283424, shards: 17714 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 40580,
      gold: 480,
      shards: 422,
      basicOreha: 14,
      crystals: 1144,
      greatLeapStone: 24,
    }),
    fromLevel: 16,
    toLevel: 17,
    chance: {
      maxAttempts: 15,
      start: 10,
      increase: 1,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 384192, shards: 24012 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 41460,
      gold: 540,
      shards: 572,
      basicOreha: 16,
      crystals: 1144,
      greatLeapStone: 28,
    }),
    fromLevel: 17,
    toLevel: 18,
    chance: {
      maxAttempts: 26,
      start: 5,
      increase: 0.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 524384, shards: 32774 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 42360,
      gold: 640,
      shards: 776,
      basicOreha: 18,
      crystals: 1300,
      greatLeapStone: 30,
    }),
    fromLevel: 18,
    toLevel: 19,
    chance: {
      maxAttempts: 26,
      start: 5,
      increase: 0.5,
    },
  },
  {
    rarirty: Rarity.Legendary,
    itemType: 'weapon',
    feed: feed({ silver: 712224, shards: 44514 }),
    upgrade: upgradeLegendary('weapon', {
      silver: 43260,
      gold: 730,
      shards: 1054,
      basicOreha: 20,
      crystals: 1300,
      greatLeapStone: 32,
    }),
    fromLevel: 19,
    toLevel: 20,
    chance: {
      maxAttempts: 40,
      start: 3,
      increase: 0.3,
    },
  },
];

export const relicWeaponHoningCosts: SingleLevelHoning[] = [
  {
    rarirty: Rarity.Relic,
    itemType: 'weapon',
    feed: feed({ silver: 967680, shards: 60480 }),
    upgrade: upgradeRelic('weapon', {
      silver: 44200,
      gold: 750,
      shards: 1432,
      basicOreha: 22,
      crystals: 1300,
      greatLeapStone: 34,
    }),
    fromLevel: 20,
    toLevel: 21,
    chance: {
      maxAttempts: 40,
      start: 3,
      increase: 0.3,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'weapon',
    feed: feed({ silver: 1317952, shards: 82372 }),
    upgrade: upgradeRelic('weapon', {
      silver: 45160,
      gold: 780,
      shards: 1944,
      basicOreha: 26,
      crystals: 1458,
      greatLeapStone: 38,
    }),
    fromLevel: 21,
    toLevel: 22,
    chance: {
      maxAttempts: 111,
      start: 1,
      increase: 0.1,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'weapon',
    feed: feed({ silver: 1789792, shards: 111862 }),
    upgrade: upgradeRelic('weapon', {
      silver: 46140,
      gold: 810,
      shards: 2640,
      basicOreha: 28,
      crystals: 1458,
      greatLeapStone: 42,
    }),
    fromLevel: 22,
    toLevel: 23,
    chance: {
      maxAttempts: 112,
      start: 1,
      increase: 0.1,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'weapon',
    feed: feed({ silver: 2431136, shards: 151946 }),
    upgrade: upgradeRelic('weapon', {
      silver: 47160,
      gold: 840,
      shards: 3586,
      basicOreha: 32,
      crystals: 1458,
      greatLeapStone: 44,
    }),
    fromLevel: 23,
    toLevel: 24,
    chance: {
      maxAttempts: 219,
      start: 0.5,
      increase: 0.05,
    },
  },
  {
    rarirty: Rarity.Relic,
    itemType: 'weapon',
    feed: feed({ silver: 3307008, shards: 206688 }),
    upgrade: upgradeRelic('weapon', {
      silver: 48180,
      gold: 870,
      shards: 4868,
      basicOreha: 36,
      crystals: 1614,
      greatLeapStone: 48,
    }),
    fromLevel: 24,
    toLevel: 25,
    chance: {
      maxAttempts: 219,
      start: 0.5,
      increase: 0.05,
    },
  },
];

export const weaponHoningCosts = [
  ...legendaryWeaponHoningCosts,
  ...relicWeaponHoningCosts,
];
