import { Rarity } from '../models';
import { Material, MaterialType } from './models';

export const materials: Material[] = [
  {
    type: MaterialType.HarmonyShardPouchSmall,
    name: 'Harmony Shard Pouch (S)',
    rarity: Rarity.Uncommon,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.HarmonyShardPouchMedium,
    name: 'Harmony Shard Pouch (M)',
    rarity: Rarity.Rare,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.HarmonyShardPouchLarge,
    name: 'Harmony Shard Pouch (L)',
    rarity: Rarity.Epic,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.LifeShardPouchSmall,
    name: 'Life Shard Pouch (S)',
    rarity: Rarity.Uncommon,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.LifeShardPouchMedium,
    name: 'Life Shard Pouch (M)',
    rarity: Rarity.Rare,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.LifeShardPouchLarge,
    name: 'Life Shard Pouch (L)',
    rarity: Rarity.Epic,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.HonorShardPouchSmall,
    name: 'Honor Shard Pouch (S)',
    rarity: Rarity.Uncommon,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.HonorShardPouchMedium,
    name: 'Honor Shard Pouch (M)',
    rarity: Rarity.Rare,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.HonorShardPouchLarge,
    name: 'Honor Shard Pouch (L)',
    chaosDungeonShards: 500,
    rarity: Rarity.Epic,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.DestructionStoneCrystal,
    name: 'Destruction Stone Crystal',
    chaosDungeonShards: 60,
    saleAmount: 10,
    rarity: Rarity.Common,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.GuardianStoneCrystal,
    name: 'Guardian Stone Crystal',
    chaosDungeonShards: 10,
    saleAmount: 10,
    rarity: Rarity.Common,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.CaldarrFusionMaterial,
    name: 'Caldarr Fusion Material',
    rarity: Rarity.Rare,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.SimpleOrehaFusionMaterial,
    name: 'Simple Oreha Fusion Material',
    rarity: Rarity.Uncommon,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.BasicOrehaFusionMaterial,
    name: 'Basic Oreha Fusion Material',
    rarity: Rarity.Rare,
    category: 'honingMaterials',
  },
  {
    type: MaterialType.SolarGrace,
    name: 'Solar Grace',
    chaosDungeonShards: 550,
    rarity: Rarity.Uncommon,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.StarsBreath,
    name: "Star's Breath",
    rarity: Rarity.Epic,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.MoonsBreath,
    name: "Moon's Breath",
    rarity: Rarity.Epic,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.HonorLeapstone,
    name: 'Honor Leapstone',
    chaosDungeonShards: 100,
    rarity: Rarity.Rare,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.GreatHonorLeapstone,
    name: 'Great Honor Leapstone',
    chaosDungeonShards: 130,
    rarity: Rarity.Rare,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.SolarBlessing,
    name: 'Solar Blessing',
    chaosDungeonShards: 570,
    rarity: Rarity.Rare,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.SolarProtection,
    name: 'Solar Protection',
    chaosDungeonShards: 590,
    rarity: Rarity.Epic,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.TailoringBasicMending,
    name: 'Tailoring Basic Mending',
    rarity: Rarity.Epic,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.TailoringAppliedMending,
    name: 'Tailoring Applied Mending',
    rarity: Rarity.Legendary,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.MetallurgyBasicWelding,
    name: 'Metalurgy Basic Welding',
    rarity: Rarity.Epic,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.MetallurgyAppliedWelding,
    name: 'Metallurgy Applied Welding',
    rarity: Rarity.Legendary,
    category: 'additionalHoningMaterials',
  },
  {
    type: MaterialType.PowderOfSage,
    name: 'Powder of Sage',
    chaosDungeonShards: 1470,
    rarity: Rarity.Epic,
    category: 'otherMaterials',
  },
  {
    type: MaterialType.HPPotion,
    name: 'HP Potion',
    rarity: Rarity.Common,
    category: 'recoveryBattleItem',
  },
  {
    type: MaterialType.MajorHPPotion,
    name: 'Major HP Potion',
    rarity: Rarity.Rare,
    category: 'recoveryBattleItem',
  },
  {
    type: MaterialType.ElementalHPPotion,
    name: 'Elemental HP Potion',
    rarity: Rarity.Epic,
    category: 'recoveryBattleItem',
  },
  {
    type: MaterialType.DestructionBomb,
    name: 'Destruction Bomb',
    rarity: Rarity.Rare,
    category: 'offenseBattleItem',
  },
  {
    type: MaterialType.WhirlwindGrenade,
    name: 'Whirlwind Grenade',
    rarity: Rarity.Rare,
    category: 'offenseBattleItem',
  },
  {
    type: MaterialType.PheromoneBomb,
    name: 'Pheromone Bomb',
    rarity: Rarity.Rare,
    category: 'utilityBattleItem',
  },
  {
    type: MaterialType.Flare,
    name: 'Flare',
    rarity: Rarity.Uncommon,
    category: 'utilityBattleItem',
  },
  {
    type: MaterialType.SacredCharm,
    name: 'Sacred Charm',
    rarity: Rarity.Rare,
    category: 'utilityBattleItem',
  },
  {
    type: MaterialType.WildFlower,
    name: 'Wild Flower',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'foraging',
  },
  {
    type: MaterialType.ShyWildFlower,
    name: 'Shy Wild Flower',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'foraging',
  },
  {
    type: MaterialType.BrightWildFlower,
    name: 'Bright Wild Flower',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'foraging',
  },
  {
    type: MaterialType.CrudeMushroom,
    name: 'Crude Mushroom',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'foraging',
  },
  {
    type: MaterialType.FreshMushroom,
    name: 'Fresh Mushroom',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'foraging',
  },
  {
    type: MaterialType.ExquisiteMushroom,
    name: 'Exquisite Mushroom',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'foraging',
  },
  {
    type: MaterialType.Timber,
    name: 'Timber',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'logging',
  },
  {
    type: MaterialType.TenderTimber,
    name: 'Tender Timber',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'logging',
  },
  {
    type: MaterialType.SturdyTimber,
    name: 'Sturdy Timber',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'logging',
  },
  {
    type: MaterialType.IronOre,
    name: 'Iron Ore',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'mining',
  },
  {
    type: MaterialType.HeavyIronOre,
    name: 'Heavy Iron Ore',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'mining',
  },
  {
    type: MaterialType.StrongIronOre,
    name: 'Strong Iron Ore',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'mining',
  },
  {
    type: MaterialType.ThickRawMeat,
    name: 'Thick Raw Meat',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'hunting',
  },
  {
    type: MaterialType.ToughLeather,
    name: 'Tough Leather',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'hunting',
  },
  {
    type: MaterialType.TreatedMeat,
    name: 'Treated Meat',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'hunting',
  },
  {
    type: MaterialType.CaldarrThickRawMeat,
    name: 'Caldarr Thick Raw Meat',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'hunting',
  },
  {
    type: MaterialType.OrehaThickMeat,
    name: 'Oreha Thick Meat',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'hunting',
  },
  {
    type: MaterialType.NaturalPearl,
    name: 'Natural Pearl',
    rarity: Rarity.Common,
    saleAmount: 10,
    category: 'fishing',
  },
  {
    type: MaterialType.CaldarrSolarCarp,
    name: 'Caldarr Solar Carp',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'fishing',
  },
  {
    type: MaterialType.Fish,
    name: 'Fish',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'fishing',
  },
  {
    type: MaterialType.RedfleshFish,
    name: 'Redflesh Fish',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'fishing',
  },
  {
    type: MaterialType.OrehaSolarCarp,
    name: 'Oreha Solar Carp',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'fishing',
  },
  {
    type: MaterialType.CaldarrRelic,
    name: 'Caldarr Relic',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'excavating',
  },
  {
    type: MaterialType.RareRelic,
    name: 'Rare Relic',
    rarity: Rarity.Uncommon,
    saleAmount: 10,
    category: 'excavating',
  },
  {
    type: MaterialType.AncientRelic,
    name: 'Ancient Relic',
    rarity: Rarity.Common,
    saleAmount: 100,
    category: 'excavating',
  },
  {
    type: MaterialType.OrehaRelic,
    name: 'Oreha Relic',
    rarity: Rarity.Rare,
    saleAmount: 10,
    category: 'excavating',
  },
];
